language: php
php:
- 5.6
- 7.0
services:
- mysql
before_script:
- cp .env.travis .env
- mysql -e 'create database avm;'
- composer self-update
- composer install --no-interaction
- php artisan migrate --seed
script: vendor/bin/phpunit
addons:
  ssh_known_hosts: rasouza.com.br
before_deploy:
- openssl aes-256-cbc -K $encrypted_7efdfd41adca_key -iv $encrypted_7efdfd41adca_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -rz --exclude '.*' --include '.env.example' --delete-after --quiet -e 'ssh -p 2222 -o "StrictHostKeyChecking no"'
    $TRAVIS_BUILD_DIR/ rasouebp@rasouza.com.br:avminventarios.com.br/sts/
  on:
    branch: master
